version: "3.9"

services:
  app:
    build: .
    container_name: om-crud-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/omdb
      SPRING_DATASOURCE_USERNAME: omuser
      SPRING_DATASOURCE_PASSWORD: ompass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: om-postgres
    restart: always
    environment:
      POSTGRES_DB: omdb
      POSTGRES_USER: omuser
      POSTGRES_PASSWORD: ompass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
